services:
  redis:
    image: bitnami/redis:latest
    container_name: redis  
    volumes:
      - ./data:/bitnami/redis/data
      # - ./conf/redis-default.conf:/opt/bitnami/redis/etc/redis-default.conf
      - ./conf/redis-bitnami.conf:/opt/bitnami/redis/etc/redis.conf
    ports:
      - 6379:6379
    restart: "no"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no